
version: 0.2

env:
  variables:
    CI: "true"

phases:
  pre_build:
    commands:
      - export REACT_APP_GMAP_KEY=$(aws kms decrypt --ciphertext-blob fileb://config/gmaps --output text --query Plaintext | base64 --decode)
      - npm install
  build:
    commands:
      - npm run test
      - npm run build
  post_build:
    commands:
      - aws s3 cp build/ s3://project-beer/ --recursive
